# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-15 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToCNB',
            fields=[
                ('datetime', models.DateTimeField()),
                ('name', models.CharField(max_length=20)),
                ('occupancy', models.IntegerField()),
                ('phoneNumber', models.CharField(max_length=11, primary_key=True, serialize=False)),
            ],
        ),
    ]
