# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-15 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_tocnb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('phoneNumberListing', models.IntegerField(primary_key=True, serialize=False)),
                ('userPhone', models.IntegerField()),
                ('userName', models.CharField(max_length=20)),
            ],
        ),
    ]
