# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phoneNumberListing',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='userPhone',
            field=models.CharField(max_length=20),
        ),
    ]
