# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20170415_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToCampus',
            fields=[
                ('datetime', models.DateTimeField()),
                ('name', models.CharField(max_length=20)),
                ('occupancy', models.IntegerField()),
                ('phoneNumber', models.CharField(max_length=11, primary_key=True, serialize=False)),
            ],
        ),
    ]
